ENH: cluster-features-open-reference
qiime2/q2-vsearch pull request #30
Opened 2017-11-14 20:11 UTC by thermokarst

Adds a new pipeline that performs open reference OTU clustering using
the `cluster-features-closed-reference` and `cluster-features-de-novo`.

2017-11-15 18:26 UTC, gregcaporaso requested changes
This is a partial review - will follow up with additional review of the unit tests.

2017-11-15 18:26 UTC, gregcaporaso commented on q2_vsearch/_cluster_features.py
> +    # Create a second in-memory table with the following schema (including
What do you mean by _including dummy data_ here?

2017-11-15 18:26 UTC, gregcaporaso commented on q2_vsearch/_cluster_features.py
> +        if tmp_unmatched_seqs.tell() > 0:
Can you explain in a comment what's going on with `seek` and `tell` here? It looks like you're seeking to the end of the file (though I don't get why) and then checking if you're at a position greater than `0` (and if not, it's an empty file). Could you just be checking the file's size here? That seems like it would be clearer (but I'm thinking I might be missing a reason why it's not possible).

2017-11-15 18:26 UTC, gregcaporaso commented on q2_vsearch/plugin_setup.py
> +        'new_reference_sequences': 'The new reference sequences.',
_The new reference sequences._

to:

_The new reference sequences. This can be used for subsequent runs of open-reference clustering for consistent definitions of features across open-reference feature tables._

2017-11-15 18:26 UTC, gregcaporaso commented on q2_vsearch/plugin_setup.py
> +                'of each cluster. See the vsearch documentation for details '
_Feature identifiers and ... of each cluster._

to:

_Feature identifiers will be inherited from the centroid feature of each cluster. For features that match a reference sequence, the centroid feature is that reference sequence, so its identifier will become the feature identifier. The clustered_sequences result will contain feature representative sequences that are derived from the sequences input for all features in clustered_table. This will always be the most abundant sequence in the cluster. The new_reference_sequences result will contain the entire reference database, plus feature representative sequences for any de novo features. This is intended to be used as a reference database in subsequent iterations of cluster_features_open_reference, if applicable._

2017-11-15 18:26 UTC, gregcaporaso commented on q2_vsearch/tests/test_cluster_features.py
> +class ClusterFeaturesOpenReference(TestPluginBase):
I think you need an additional test here for the case when no sequences hit the reference (so all are clustered de novo).

2017-11-15 18:26 UTC, gregcaporaso commented on q2_vsearch/_cluster_features.py
> +    return table, matched_seqs, unmatched_seqs
It looks like there is a bug in the `matched_seqs` output, where some sequences can be reported multiple times. @thermokarst and I are communicating offline about this, but just wanted to add a note for the record here.

2017-11-15 20:56 UTC, gregcaporaso requested changes
These suggestions were made during pair review with @thermokarst.

2017-11-15 20:56 UTC, gregcaporaso commented on q2_vsearch/tests/test_cluster_features.py
> +        self.exp_seqs = _read_seqs(self.input_sequences)
I think we should change the name `self.exp_seqs` - maybe `self.input_sequences_list` (which also isn't ideal, but we have the input sequences as two different types here).

2017-11-15 20:56 UTC, gregcaporaso commented on q2_vsearch/tests/test_cluster_features.py
> +    def test_highest_count_clustering(self):
Let's call this `test_1_percent_clustering_alt_abundances` and move it up so it's next to `test_1_percent_clustering`. 

Maybe the comment can note which specific feature is now most abundant, and how that changes the result.

2017-11-15 20:56 UTC, gregcaporaso commented on q2_vsearch/tests/test_cluster_features.py
> +    def test_97_percent_clustering(self):
This test, paired with `test_100_percent_clustering`, shows that `perc_identity` is impacting closed-reference clustering. Could you add a `feature5` that clusters with `feature2` at 97% identity, but not at 100% identity, so we can see that `perc_identity` is also impacting de novo clustering?

2017-11-15 20:56 UTC, gregcaporaso commented on q2_vsearch/tests/test_cluster_features.py
> +        exp_ref_seqs = [self.exp_seqs[1], self.exp_seqs[2], ref_seqs[0],
Build `exp_ref_seqs` as follows (in all cases) so you know that all `ref_seqs` are always in `exp_ref_seqs`:

`exp_ref_seqs = [self.exp_seqs[1], self.exp_seqs[2]] + ref_seqs`

2017-11-17 21:54 UTC, thermokarst commented
Thanks @gregcaporaso, there are a handful of individual squash commits now available in this PR, for your reviewing pleasure. `#ThanksGreg!`

2017-11-20 17:40 UTC, gregcaporaso commented on q2_vsearch/_cluster_features.py
> +    return table, matched_seqs, unmatched_seqs
Confirmed that this bug is no longer present.

2017-11-20 17:46 UTC, gregcaporaso requested changes

2017-11-20 17:46 UTC, gregcaporaso commented on q2_vsearch/tests/test_cluster_features.py
> +        # features so de-novo clustering is skipped.
Looks like copy/paste error with this comment.

2017-11-20 17:46 UTC, gregcaporaso commented on q2_vsearch/tests/test_cluster_features.py
> +        # The returned "new" ref seqs should be the same as the original rep
This is wrong, we still want the ref_seqs to include the full reference - that's always the case (this process can only increase the size of the reference, not decrease it).

2017-11-20 17:47 UTC, gregcaporaso commented on q2_vsearch/tests/test_cluster_features.py
> +        # features so de-novo clustering is skipped.
Oops, I think I was reviewing a single commit, sorry! Ignore this if it's already fixed.

2017-11-20 17:53 UTC, gregcaporaso requested changes

2017-11-20 17:53 UTC, gregcaporaso commented on q2_vsearch/_cluster_features.py
> +    if unmatched_seqs.view(pd.Series).size:
Could you add `> 0`, so this is more explicit?

2017-11-20 17:53 UTC, gregcaporaso commented on q2_vsearch/_cluster_features.py
> +            outputs = (de_novo_table, de_novo_seqs, de_novo_seqs)
This should still include:

```
merged_reference_seqs, = merge_seq_data(data1=reference_sequences, data2=de_novo_seqs)
```

(Same issue I commented about on the test code.)

2017-11-20 22:47 UTC, thermokarst commented
Thanks @gregcaporaso! I addressed your latest round of comments in [this commit](https://github.com/qiime2/q2-vsearch/pull/30/commits/e85b688e073335070b382babf887ce3dbcbec407).

2017-11-20 23:25 UTC, gregcaporaso approved these changes

2017-11-20 23:27 UTC, merged

2017-11-20 23:27 UTC, gregcaporaso commented
Thanks @thermokarst!