ENH: adds --prefix dereplication parameter
qiime2/q2-vsearch pull request #54
Opened 2018-07-25 23:38 UTC by colinbrislawn

First time plug-in development. Feedback wanted!

When finished, resolves #24 

This does not yet have unit tests, I have not done linting, and I'm not sure if it's stylistically consistent. I appreciate _any_ comments and suggestions.

2018-08-11 21:34 UTC, thermokarst requested changes
This looks awesome @colinbrislawn! I have one minor naming request, inline, otherwise this looks good to me! Thanks so much!

2018-08-11 21:34 UTC, thermokarst commented on q2_vsearch/_cluster_sequences.py
> +                          prefix: bool=False
Can we rename this param to `derep_prefix`, to match the `vsearch`-given name? We have been trying to do that when exposing params on 3rd-party tools like this.

2018-08-11 21:34 UTC, thermokarst commented on q2_vsearch/plugin_setup.py
> +        'prefix': qiime2.plugin.Bool,
Please see my request above RE renaming this to `derep_prefix`.

2018-08-17 20:04 UTC, colinbrislawn commented
@thermokarst How's it look? I'm excited to merge my first unit test!

2018-08-23 13:22 UTC, thermokarst approved these changes

2018-08-23 13:22 UTC, merged

2018-08-23 13:23 UTC, thermokarst commented
Thanks @colinbrislawn! Can you take a few minutes to [update the changelog](https://forum.qiime2.org/t/preview-qiime-2-2018-8-development-changelog/4724?u=thermokarst)? Let me know if you have any questions. Thanks!

2018-08-23 17:58 UTC, colinbrislawn commented
I've updated the changelog! Thank you for your support Matt.

2018-08-28 19:35 UTC, gregcaporaso commented
Thanks for the contribution @colinbrislawn!